### ISSUE TITLE
Samsung S7 Edge not giving permissions to the app

### ISSUE THREAD

**Issue by pigottlaura** [wishiwashere/TeamProject-2016#6]
Testing on the Samsung S7 Edge, the camera is not being activated as the device is not giving the permissions to the app. If the user goes into their app settings, they can manually turn these on and the device will work. Need to look at triggering a request to the user to turn these permissions on for our app

**Comment by eirenmc** [comment]
As of the latest android version release - Marshmallow (6.0) Any apps that require access to the users device functionality such as camera and storage need to request permission from the user in order to access these functionalities. In order to overcome this issue, we are checking to see if the users device requires these 'dangerous permissions' and if so, ask the user to grant permission and if not, carry on as normal. If the app doesn't require these dangerous permission this is due to the fact the device has a running API of 23 or higher
